In [ ]:
import pandas as pd

,ten_nhiem_vu,don_vi_chu_tri,don_vi_phoi_hop,thoi_han,nhom_nhiem_vu,nhom_so_thu_tu,ma_nhiem_vu
0,Xây dựng kế hoạch di trú dữ liệu sau\nkhi chốt...,Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",7,NaN,NaN,NaN
1,"Đảm bảo hạ tầng theo Sizing, các\ngiải pháp ph...",Sở\nKHCN,Sở Y tế,30,NaN,NaN,NaN
2,Đảm bảo đường truyền kết nối từ hạ\ntầng triển...,Sở\nKHCN,Sở Y tế,Sở\nKHCN\nđưa ra\nkế hoạch,NaN,NaN,NaN
3,Đảm bảo đầu số SMS Brandname\nphục vụ đảm bảo ...,Sở\nKHCN,Sở Y tế,Sở\nKHCN\nđưa ra\nkế hoạch,NaN,NaN,NaN
4,"Cài đặt Hệ điều hành, K8S hoặc thuê\ngói cài đặt",Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",7,NaN,NaN,NaN
5,Cài đặt CSDL và ứng dụng,Tập đoàn\nViettel,Sở Y tế,10,NaN,NaN,NaN
6,"Phối hợp với Bộ Công An, Bộ\nKHCN đánh giá ATT...",Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",30,NaN,NaN,NaN
7,Xây dựng công văn về chuyển dữ\nliệu từ TTDL T...,Sở Y tế,Tập đoàn\nViettel,5,NaN,NaN,NaN
8,"Thống nhất quy trình tiếp nhận dữ\nliệu, đầu m...",Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",5,NaN,NaN,NaN
9,Cập nhật lại dữ liệu từ CSDL được\nTập đoàn Vi...,Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",10,NaN,NaN,NaN
10,Chạy thử và vận hành thử,Sở Y tế,Tập đoàn\nViettel,10,NaN,NaN,NaN
11,Ký biên bản kết thúc di trú dữ liệu,Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",1,NaN,NaN,NaN

In [19]:
t=pd.read_csv(r"C:\GEO\Parsing data from PDF\data\output\cv6582_normalized.csv")
t

,ten_nhiem_vu,don_vi_chu_tri,don_vi_phoi_hop,thoi_han,nhom_nhiem_vu,nhom_so_thu_tu,ma_nhiem_vu
0,Xây dựng kế hoạch di trú dữ liệu sau\nkhi chốt...,Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",7,NaN,NaN,NaN
1,"Đảm bảo hạ tầng theo Sizing, các\ngiải pháp ph...",Sở\nKHCN,Sở Y tế,30,NaN,NaN,NaN
2,Đảm bảo đường truyền kết nối từ hạ\ntầng triển...,Sở\nKHCN,Sở Y tế,Sở\nKHCN\nđưa ra\nkế hoạch,NaN,NaN,NaN
3,Đảm bảo đầu số SMS Brandname\nphục vụ đảm bảo ...,Sở\nKHCN,Sở Y tế,Sở\nKHCN\nđưa ra\nkế hoạch,NaN,NaN,NaN
4,"Cài đặt Hệ điều hành, K8S hoặc thuê\ngói cài đặt",Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",7,NaN,NaN,NaN
5,Cài đặt CSDL và ứng dụng,Tập đoàn\nViettel,Sở Y tế,10,NaN,NaN,NaN
6,"Phối hợp với Bộ Công An, Bộ\nKHCN đánh giá ATT...",Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",30,NaN,NaN,NaN
7,Xây dựng công văn về chuyển dữ\nliệu từ TTDL T...,Sở Y tế,Tập đoàn\nViettel,5,NaN,NaN,NaN
8,"Thống nhất quy trình tiếp nhận dữ\nliệu, đầu m...",Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",5,NaN,NaN,NaN
9,Cập nhật lại dữ liệu từ CSDL được\nTập đoàn Vi...,Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",10,NaN,NaN,NaN
10,Chạy thử và vận hành thử,Sở Y tế,Tập đoàn\nViettel,10,NaN,NaN,NaN
11,Ký biên bản kết thúc di trú dữ liệu,Sở Y tế,"Sở KHCN,\nTập đoàn\nViettel",1,NaN,NaN,NaN

In [20]:
d=pd.read_csv(r"C:\GEO\Parsing data from PDF\data\output\kh277_normalized.csv")
d

,ten_nhiem_vu,don_vi_chu_tri,don_vi_phoi_hop,san_pham,thoi_han,nhom_nhiem_vu,nhom_so_thu_tu,ma_nhiem_vu
0,"Dữ liệu đầu tư công, thu ngân sách, dự án đầu\...",Sở Tài chính,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1a
1,Dữ liệu quy hoạch,Sở Quy hoạch -\nKiến trúc,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1b
2,"Dữ liệu đất đai, địa chính, môi trường",Sở Nông nghiệp và\nMôi trường,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1c
3,"Dữ liệu xây dựng, hạ tầng kỹ thuật, giao thông...",Sở Xây\ndựng/các công\nty quản lý lĩnh\nvực li...,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1d
4,"Hồ sơ, kết quả giải quyết TTHC","Trung tâm Phục vụ\nhành chính công, Sở,\nban, ...",Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1đ
5,Dữ liệu quản lý văn bản và điều hành (QLVB),Văn phòng UBND\nThành phố,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1e
6,Dữ liệu y tế,Sở Y tế,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1g
7,Dữ liệu giáo dục,Sở Giáo dục\nvà Đào tạo,Sở Khoa học và\nCông nghệ,"Hoàn thành tích hợp, di trú và\nchuẩn hóa dữ l...",30/8/2026,"Làm sạch, di trú, tích hợp, chuẩn hóa nhóm\ndữ...",1,1h
8,"Đối với khoảng 3,2 triệu thửa đất (đã được đo\...",Sở Nông nghiệp và\nMôi trường,"UBND xã/phường,\nCông an Thành phố,\nSở Khoa h...","Dữ liệu đạt tiêu chí “đúng, đủ,\nsạch, sống”",30/7/2026,Tập trung cao điểm “45 ngày” về hoàn thiện\ncơ...,2,2a
9,Đối với khoảng 950.000 thửa đất còn lại đang\n...,Sở Nông nghiệp và\nMôi trường,"UBND xã/phường,\nCông an Thành phố,\nSở Khoa h...","Dữ liệu đạt tiêu chí “đúng, đủ,\nsạch, sống”",30/8/2026,Tập trung cao điểm “45 ngày” về hoàn thiện\ncơ...,2,2b
10,"Tổng rà soát, kiểm kê, đánh giá hiện trạng các...",Sở Khoa học và\nCông nghệ,"Các Sở, ban, ngành,\ncác đơn vị quản lý\nhệ thống","Danh mục phần mềm, hệ thống giữ\nlại, tích hợp...",100 ngày kể\ntừ ngày ban\nhành Kế\nhoạch,"Chuẩn hóa, tích hợp và liên thông hệ thống\nth...",3,3a
11,"Xây dựng, triển khai hệ thống xác thực định\nd...",Sở Khoa học và\nCông nghệ,Công an Thành phố;\nVăn phòng UBND\nThành phố;...,"Hoàn thành việc triển khai IDP, có\nthể đăng n...",100 ngày kể\ntừ ngày ban\nhành Kế\nhoạch,"Chuẩn hóa, tích hợp và liên thông hệ thống\nth...",3,3b
12,Tích hợp Không gian làm việc số HanoiWork\nvới...,Sở Khoa học và\nCông nghệ,"Văn phòng Thành\nủy, Văn phòng\nHĐND Thành phố...",Hoàn thành tích hợp kỹ thuật đảm\nbảo thông su...,30/9/2026,"Chuẩn hóa, tích hợp và liên thông hệ thống\nth...",3,3c
13,Cung cấp dịch vụ công trực tuyến và đơn giản\n...,"Trung tâm Phục vụ\nhành chính công,\ncác Sở, b...","Đề nghị phối hợp\nvới các Bộ, ngành\nliên quan",- 100% được cung cấp trực tuyến;\n80% được cun...,100 ngày kể\ntừ ngày ban\nhành Kế\nhoạch,"Lựa chọn nhóm TTHC có tần suất cao, liên\nquan...",4,4a
14,100% hồ sơ phát sinh của nhóm 05 thủ tục giao\...,"Trung tâm Phục vụ\nhành chính công, Sở\nNông n...","Đề nghị phối hợp\nvới các Bộ, ngành\nliên quan",100% hồ sơ phát sinh trực tuyến\ntoàn trình,100 ngày kể\ntừ ngày ban\nhành Kế\nhoạch,"Lựa chọn nhóm TTHC có tần suất cao, liên\nquan...",4,4b
15,Thí điểm miễn cấp phép xây dựng đối với các\nd...,"UBND các xã,\nphường",Sở Xây dựng,"Thí điểm tại 126 xã, phường",100 ngày kể từ\nngày ban hành\nKế hoạch,"Lựa chọn nhóm TTHC có tần suất cao, liên\nquan...",4,4c
16,"Đối với TTHC lấy ý kiến liên ngành, áp dụng\nt...","Các cơ quan, đơn vị\ngiải quyết TTHC",NaN,"Không để phát sinh hồ sơ chậm,\nmuộn do quá th...",Từ ngày ban\nhành Kế hoạch\ntrở đi,"Lựa chọn nhóm TTHC có tần suất cao, liên\nquan...",4,4d
17,"Xúc tiến, tháo gỡ và triển khai các dự án đầu\...","Sở Tài chính, Ban\nQuản lý các Khu\ncông nghệ ...","Sở Khoa học và\nCông nghệ, Sở Công\nThương, Sở...",- Phấn đấu 03-05 dự án quy mô lớn\nđược chấp t...,100 ngày kể\ntừ ngày ban\nhành Kế\nhoạch,Thu hút đầu tư và xúc tiến xuất khẩu trong\nlĩ...,5,5a
18,Hỗ trợ doanh nghiệp công nghệ số Hà Nội\nxuất ...,Sở Công Thương,"Sở Khoa học và\nCông nghệ, Sở Tài\nchính",- Tối thiểu 20 doanh nghiệp công\nnghệ số Hà N...,100 ngày kể\ntừ ngày ban\nhành Kế\nhoạch,Thu hút đầu tư và xúc tiến xuất khẩu trong\nlĩ...,5,5b
19,"Hỗ trợ chuyển đổi số cho hộ kinh doanh, doanh\...","UBND các xã,\nphường",Sở Khoa học và Công\nnghệ; Sở Tài chính;\nSở C...,"Mỗi xã, phường bảo đảm tối thiểu\n30% hộ kinh ...",100 ngày kể từ\nngày ban hành\nKế hoạch,Cao điểm chuyển đổi số hoạt động kinh\ndoanh c...,6,6a
20,Tiếp tục triển khai đợt cao điểm hiện đại hóa\...,Thuế Hà Nội,"Sở Khoa học và Công\nnghệ, UBND các xã,\nphường",- 100% nhóm hộ có doanh thu trên\n1 tỷ đồng sử...,100 ngày kể từ\nngày ban hành\nKế hoạch,Cao điểm chuyển đổi số hoạt động kinh\ndoanh c...,6,6b
21,"Triển khai đợt cao điểm các chợ, tuyến phố\nki...","UBND các xã,\nphường","Sở Khoa học và Công\nnghệ, Thuế Hà Nội,\nTrung...","- 100% chợ dân sinh trên địa bàn\n126 xã, phườ...",100 ngày kể từ\nngày ban hành\nKế hoạch,Cao điểm chuyển đổi số hoạt động kinh\ndoanh c...,6,6c
22,"Triển khai AI hỗ trợ kinh doanh, bán hàng và\n...",Sở Khoa học và\nCông nghệ,"Sở Tài chính, Sở\nCông Thương, sở,\nngành có l...",- Triển khai tối thiểu 01 bộ công cụ\nAI hỗ tr...,100 ngày kể từ\nngày ban hành\nKế hoạch,Cao điểm chuyển đổi số hoạt động kinh\ndoanh c...,6,6d
23,Triển khai “Gian hàng sản phẩm Thủ đô Hà\nNội”...,Sở Công Thương,"Sở Nông nghiệp và\nMôi trường, Sở Khoa\nhọc và...",Khai trương các gian hàng,31/7/2026,"Cao điểm phát triển thương mại điện tử,\nquảng...",7,7a
24,"Hỗ trợ đưa sản phẩm OCOP, sản phẩm của\nlàng n...","UBND các xã,\nphường","Sở Công Thương, Sở\nKhoa học và Công\nnghệ, Sở...","Mỗi xã, phường bảo đảm hỗ trợ đưa\ntối thiểu 0...",100 ngày kể từ\nngày ban hành\nKế hoạch,"Cao điểm phát triển thương mại điện tử,\nquảng...",7,7b
25,Tổ chức các buổi livestream có sự tham gia của...,"UBND các xã,\nphường","Sở Công Thương, Sở\nKhoa học và Công\nnghệ, Sở...","- 126 xã, phường tổ chức sự kiện\nlivestreams ...",100 ngày kể từ\nngày ban hành\nKế hoạch,"Cao điểm phát triển thương mại điện tử,\nquảng...",7,7c
26,Tổ chức “Tháng khuyến mại số Hà Nội” trên\ncơ ...,Sở Công Thương,Sở Khoa học và\nCông nghệ; Sở Nông\nnghiệp và ...,- Tổ chức thành công 01 đợt cao\nđiểm khuyến m...,100 ngày kể từ\nngày ban hành\nKế hoạch,"Cao điểm phát triển thương mại điện tử,\nquảng...",7,7d
27,Phát triển kinh tế đêm sáng tạo\nTriển khai th...,Sở Văn hóa và\nThể thao,"Sở Du lịch, Sở Khoa\nhọc và Công nghệ,\ncác đơ...",02 mô hình kinh tế đêm sáng tạo\nđược triển kh...,100 ngày kể từ\nngày ban hành\nKế hoạch,Phát triển kinh tế đêm sáng tạo\nTriển khai th...,8,8
28,Phát triển mô hình du lịch số\nPhát triển mô h...,Sở Du lịch,"Sở Văn hóa và Thể\nthao, Sở Khoa học và\nCông ...",Tối thiểu 10 hoạt động/điểm du\nlịch được triể...,100 ngày kể từ\nngày ban hành\nKế hoạch,Phát triển mô hình du lịch số\nPhát triển mô h...,9,9
29,"Triển khai mô hình thôn, tổ dân phố số\nMô hìn...","UBND các xã,\nphường trực tiếp\ntriển khai tại...","UB MTTQ Việt Nam\nThành phố, MTTQ\ncấp xã và B...",Hoàn thành triển khai đối với 100%\n(khoảng 2....,100 ngày kể từ\nngày ban hành\nKế hoạch,"Triển khai mô hình thôn, tổ dân phố số\nMô hìn...",10,10
30,Triển khai hệ thống HanoiCheck\nTriển khai “Hệ...,"Sở Giáo dục và\nĐào tạo, UBND các\nxã/phường t...","Sở Nông nghiệp và\nMôi trường, Sở Giáo\ndục và...",100% cơ sở giáo dục có bếp ăn bán\ntrú trên đị...,100 ngày kể từ\nngày ban hành\nKế hoạch,Triển khai hệ thống HanoiCheck\nTriển khai “Hệ...,11,11
31,Hoàn thành đề xuất phân bổ kinh phí các\nnhiệm...,"Các Sở, ban, ngành;\nUBND các xã,\nphường","Sở Tài chính,\nSở Khoa học và\nCông nghệ",100% nhiệm vụ chuyển đổi số đã\ngiao năm 2026 ...,31/7/2026,Giải quyết dứt điểm việc phân bổ kinh phí\nvà ...,12,12a
32,Tăng tỷ lệ giải ngân ngân sách nhà nước chi\nc...,"Các Sở, ban, ngành;\nUBND các xã,\nphường","Sở Tài chính,\nSở Khoa học và\nCông nghệ",Tỷ lệ giải ngân/phân bổ đạt tối\nthiểu 40%,100 ngày,Giải quyết dứt điểm việc phân bổ kinh phí\nvà ...,12,12b